# Generated by Django 3.2 on 2022-05-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_subscribers_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailMessage',
            new_name='SendMessage',
        ),
    ]
