# Generated by Django 3.2 on 2022-06-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditComment',
        ),
    ]
