# Generated by Django 3.2 on 2022-06-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_editcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
