# Generated by Django 4.0 on 2022-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220605_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
