# Generated by Django 3.2 on 2022-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
